title: Rachel Gordon
logo:  # you can add own logo.
description:
baseurl: ""
url: https://rachelgordon.github.io # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Rachel Gordon
  image: '/assets/img/about.jpg'
  job: Hi there, welcome to my page!
  bio: |+
    <br />
    I am a Computer Science PhD student at the <a href="https://www.uchicago.edu/en">University of Chicago</a>, where I am a member of <a href="https://labs.globus.org/">Globus Labs</a>, led by <a href="https://cs.uchicago.edu/people/ian-foster/">Ian Foster</a> and <a href="https://kylechard.com/">Kyle Chard</a>.
    <br />
    <br />
    My research focuses on leveraging machine learning to improve the quality and accessibility of healthcare. Specifically, I develop deep learning models for medical imaging tasks such as image synthesis, reconstruction, and enhancement, with applications in modalities like CT and MRI. Before pursuing my PhD, I earned an MS in Data Science from <a href="https://www.luc.edu/">Loyola University Chicago</a>, where I completed my Master's thesis under the supervision of [Mohammed Abuhamad](https://abuhamad.cs.luc.edu/). I defended my work on <a href="https://drive.google.com/file/d/1DuzTBMaGBus1fUfEtWtcX2zE9R2PKcQv/view">Enhanced CT-to-MRI synthesis for High-dose-rate Brachytherapy Treatment Planning</a> with distinction. 
    <br />
  CV: https://docs.google.com/document/d/1UEjwR8iawzKzgH_3kj7bE2_wZaT39INEZ1LeXGz89HY/edit?usp=sharing
  email: rachelgordon@uchicago.edu
  github: https://github.com/rachelngordon
  linkedin: https://www.linkedin.com/in/rachelngordon/
  scholar: https://scholar.google.com/citations?view_op=list_works&hl=en&user=KNGtQP8AAAAJ&gmla=ABOlHiwO0b2ojIXNR966uozr0jvPd_E9zypv0dzWug2BDFCqsMLgSeCMIqUAh21gsUNJyivmQFimtYFadvVuMSI8cU_8h6TKlw03CTRj1D9-drHmYw
  last_update:  January 2025



# Contact links
# TODO: Potentially add later.
# contact:
#   - name: Twitter
#     link: https://twitter.com/
#

# Comment Section (Disqus)
disqus-identifier: rachelgordon # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: UA-208765987-1
# add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
